#pragma once

#include <cstdint>

enum class XDlmsApduTag : uint8_t
{
    INITIATE_REQUEST = 0x01,
    READ_REQUEST = 0x05,
    WRITE_REQUEST = 0x06,
    INITIATE_RESPONSE = 0x08,
    READ_RESPONSE = 0x0C,
    WRITE_RESPONSE = 0x0D,
    CONFIRMED_SERVICE_ERROR = 0x0E,
    DATA_NOTIFICATION = 0x0F,
    UNCONFIRMED_WRITE_REQUEST = 0x16,
    INFORMATION_REPORT_REQUEST = 0x18,

    GET_REQUEST = 0xC0,
    SET_REQUEST = 0xC1,
    EVENT_NOTIFICATION_REQUEST = 0xC2,
    ACTION_REQUEST = 0xC3,
    GET_RESPONSE = 0xC4,
    SET_RESPONSE = 0xC5,
    ACTION_RESPONSE = 0xC7,

    GLO_GET_REQUEST = 0xC8,
    GLO_SET_REQUEST = 0xC9,
    GLO_EVENT_NOTIFICATION = 0xCA,
    GLO_ACTION_REQUEST = 0xCB,
    GLO_GET_RESPONSE = 0xCC,
    GLO_SET_RESPONSE = 0xCD,
    GLO_ACTION_RESPONSE = 0xCF,

    DED_GET_REQUEST = 0xD0,
    DED_SET_REQUEST = 0xD1,
    DED_EVENT_NOTIFICATION = 0xD2,
    DED_ACTION_REQUEST = 0xD3,
    DED_GET_RESPONSE = 0xD4,
    DED_SET_RESPONSE = 0xD5,
    DED_ACTION_RESPONSE = 0xD7,

    EXCEPTION_RESPONSE = 0xD8,
    ACCESS_REQUEST = 0xD9,
    ACCESS_RESPONSE = 0xDA,
    GENERAL_GLO_CIPHERING = 0xDB,
    GENERAL_DED_CIPHERING = 0xDC,
    GENERAL_CIPHERING = 0xDD,
    GENERAL_SIGNING = 0xDF,
    GENERAL_BLOCK_TRANSFER = 0xE0,
};

enum class ServiceType : uint8_t
{
    NORMAL = 0x01,
    WITH_DATABLOCK = 0x02,
    WITH_LIST = 0x03,
    WITH_FIRST_DATABLOCK = 0x02,
    WITH_LIST_AND_FIRST_DATABLOCK = 0x05,
    LAST_DATABLOCK = 0x03,
    LAST_DATABLOCK_WITH_LIST = 0x04,
    NEXT_PBLOCK = 0x02,
    WITH_FIRST_PBLOCK = 0x04,
    WITH_LIST_AND_FIRST_PBLOCK = 0x05,
    WITH_PBLOCK = 0x06,
    WITH_OPTIONAL_DATA = 0x01,
    WITH_PBLOCK_RESPONSE = 0x02,
    WITH_LIST_RESPONSE = 0x03,
    NEXT_PBLOCK_RESPONSE = 0x04,
};

enum class Priority : uint8_t
{
    NORMAL = 0,
    HIGH = 1
};

enum class ServiceClass : uint8_t
{
    UNCONFIRMED = 0,
    CONFIRMED = 1
};
